# .streamlit/secrets.toml

# Supabase Credentials
SUPABASE_URL = "https://xthkpyggvfupefygaefk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aGtweWdndmZ1cGVmeWdhZWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MjkyMTEsImV4cCI6MjA3ODUwNTIxMX0.skVXa3bwit3Z3gRzgUK8nQOr0DnvYOdwQh_C2odNaoY"
